apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: output
  steps:
    - name: cleanup
      image: alpine:3.19
      script: |
        #!/bin/sh
        set -eux
        rm -rf "$(workspaces.output.path)"/* || true
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  workspaces:
    - name: source
  steps:
    - name: test
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -eux
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        nosetests -v --with-spec --spec-color
